# This is a basic workflow to help you get started with Actions

name: CD-fhir

on:
  workflow_dispatch:
    inputs:
      bal_central_environment:
        description: Ballerina Central Environment
        type: choice
        options:
        - STAGE
        - DEV
        - PROD
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xmx4G
    steps:
      - uses: actions/checkout@v3

      - name: Ballerina build fhir
        uses: ballerina-platform/ballerina-action@2201.7.0
        with:
          args:
            pack
        env:
          WORKING_DIR: /fhir
          JAVA_HOME: /usr/lib/jvm/default-jvm
          








      
