[package]
org = "ballerinax"
name = "health.clients.dicomclient"
version = "0.1.0"
distribution = "2201.8.2"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "health.dicom"
version = "0.1.0"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "health.dicom.dicomparser"
version = "0.1.0"
repository = "local"